"use client";
import {useMemo,useState} from "react";
type U="fixo"|"dia"|"pessoa"|"pessoa-dia"; type C={id:number;name:string;value:number;unit:U};
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const labs:Record<U,string>={fixo:"por locação",dia:"por dia",pessoa:"por pessoa","pessoa-dia":"por pessoa/dia"};
const base={stay:[{id:1,name:"Limpeza",value:180,unit:"fixo"},{id:2,name:"Lavanderia",value:25,unit:"pessoa"},{id:3,name:"Energia, água e gás",value:35,unit:"dia"},{id:4,name:"Rateio de custos fixos",value:120,unit:"dia"}] as C[],event:[{id:1,name:"Limpeza e preparação",value:100,unit:"fixo"},{id:2,name:"Consumo e estrutura",value:3,unit:"pessoa"},{id:3,name:"Equipe de apoio",value:0,unit:"dia"},{id:4,name:"Rateio de custos fixos",value:3,unit:"pessoa"}] as C[]};
const line=(c:C,p:number,d:number)=>c.value*(c.unit==="dia"?d:c.unit==="pessoa"?p:c.unit==="pessoa-dia"?p*d:1);
export default function Home(){
 const [mode,setMode]=useState<"stay"|"event">("stay"),[people,setPeople]=useState(6),[days,setDays]=useState(2),[margin,setMargin]=useState(30),[fee,setFee]=useState(0),[channel,setChannel]=useState("Direto"),[costs,setCosts]=useState<C[]>(base.stay);
 const total=useMemo(()=>costs.reduce((s,c)=>s+line(c,people,days),0),[costs,people,days]),factor=1-margin/100-fee/100,price=factor>0?total/factor:0,platform=price*fee/100,profit=price-platform-total,minimum=fee<100?total/(1-fee/100):0;
 const modeTo=(m:"stay"|"event")=>{setMode(m);setCosts(base[m]);setPeople(m==="stay"?6:50);setDays(m==="stay"?2:1);setMargin(m==="stay"?30:50);choose("Direto",0)};
 const patch=(id:number,p:Partial<C>)=>setCosts(a=>a.map(c=>c.id===id?{...c,...p}:c)); const choose=(n:string,f:number)=>{setChannel(n);setFee(f)};
 return <main><header><div className="brand"><b>L</b><span>Hospedagem & Eventos</span></div><button className="link" onClick={()=>modeTo(mode)}>Limpar simulação</button></header>
 <section className="hero"><small>CALCULADORA DE PRECIFICAÇÃO</small><h1>Do custo ao preço certo, sem complicação.</h1><p>Informe os custos e sua meta de lucro. A calculadora sugere quanto cobrar pela hospedagem ou pelo evento.</p></section>
 <nav className="tabs"><button className={mode==="stay"?"active":""} onClick={()=>modeTo("stay")}>⌂ Hospedagem</button><button className={mode==="event"?"active":""} onClick={()=>modeTo("event")}>◎ Espaço para eventos</button><button className="quickTab" onClick={()=>modeTo("event")}>⚡ Consulta rápida</button></nav>
 <section className="workspace"><div className="forms"><article className="card"><Title n="1" title="Detalhes da locação" text="Defina o tamanho desta consulta."/><div className="two"><label>Quantidade de pessoas<input type="number" min="1" value={people} onChange={e=>setPeople(Math.max(1,+e.target.value))}/></label><label>{mode==="stay"?"Quantidade de diárias":"Dias de evento"}<input type="number" min="1" value={days} onChange={e=>setDays(Math.max(1,+e.target.value))}/></label></div></article>
 <article className="card"><Title n="2" title="Todos os custos" text="Inclua somente o que realmente entra nesta locação."/><div className="costs">{costs.map(c=><div className="cost" key={c.id}><input className="name" aria-label="Nome do custo" value={c.name} onChange={e=>patch(c.id,{name:e.target.value})}/><div className="money"><span>R$</span><input aria-label={`Valor de ${c.name}`} type="number" min="0" value={c.value} onChange={e=>patch(c.id,{value:Math.max(0,+e.target.value)})}/></div><select value={c.unit} onChange={e=>patch(c.id,{unit:e.target.value as U})}>{Object.entries(labs).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select><div className="lineTotal"><small>Total</small><strong>{brl.format(line(c,people,days))}</strong></div><button className="remove" aria-label={`Excluir ${c.name}`} onClick={()=>setCosts(costs.filter(x=>x.id!==c.id))}>×</button></div>)}</div><button className="add" onClick={()=>setCosts([...costs,{id:Date.now(),name:"Novo custo",value:0,unit:"fixo"}])}>+ Adicionar outro custo</button><div className="total"><span>Custo total calculado</span><strong>{brl.format(total)}</strong></div></article>
 <article className="card"><Title n="3" title="Meta e canal de venda" text="Quanto deseja ganhar depois de pagar tudo?"/><label className="range"><span>Margem de lucro desejada <strong>{margin}%</strong></span><input type="range" min="0" max="70" value={margin} onChange={e=>setMargin(+e.target.value)}/></label><div className="channels">{[["Direto",0],["Airbnb",15],["Booking",18]].map(([n,f])=><button className={channel===n?"selected":""} key={n} onClick={()=>choose(String(n),Number(f))}><strong>{n}</strong><small>{f}% de taxa</small></button>)}</div><label className="fee">Taxa/comissão deste canal <span><input type="number" min="0" max="99" value={fee} onChange={e=>setFee(Math.max(0,+e.target.value))}/>%</span></label></article></div>
 <aside><small>PREÇO SUGERIDO</small>{factor<=0?<p className="warning">A soma da margem e da comissão precisa ser menor que 100%.</p>:<><div className="price">{brl.format(price)}</div><p className="context">para {people} {people===1?"pessoa":"pessoas"} · {days} {days===1?"dia":"dias"} · {channel}</p><div className="units"><div><span>Por dia</span><strong>{brl.format(price/days)}</strong></div><div><span>Por pessoa</span><strong>{brl.format(price/people)}</strong></div></div><div className="breakdown"><div><span>Custos</span><strong>{brl.format(total)}</strong></div><div><span>Taxa de {fee}%</span><strong>− {brl.format(platform)}</strong></div><div className="profit"><span>Seu lucro projetado</span><strong>{brl.format(profit)}</strong></div></div><div className="minimum"><span>Preço mínimo para não ter prejuízo</span><strong>{brl.format(minimum)}</strong></div><p className="privacy">Nenhum dado é salvo. Esta simulação existe somente nesta tela.</p></>}</aside></section><footer>Resultado indicativo para apoiar sua decisão. Confirme impostos e taxas aplicáveis antes de fechar a locação.</footer></main>}
function Title({n,title,text}:{n:string;title:string;text:string}){return <div className="title"><b>{n}</b><div><h2>{title}</h2><p>{text}</p></div></div>}
